// <auto-generated />
using System;
using LibraryBlazorApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryBlazorApp.Infrastructure.Migrations
{
    [DbContext(typeof(BlazorLibraryDbContext))]
    [Migration("20260329155122_AddUpdatedAtColumn")]
    partial class AddUpdatedAtColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryBlazorApp.Domain.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Addresses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Warszawa",
                            ClientId = 1,
                            Country = "Polska",
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "00-001",
                            Street = "Kwiatowa 1",
                            UpdatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            City = "Kraków",
                            ClientId = 2,
                            Country = "Polska",
                            CreatedAt = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "30-002",
                            Street = "Słoneczna 5",
                            UpdatedAt = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            City = "Gdańsk",
                            ClientId = 3,
                            Country = "Polska",
                            CreatedAt = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "80-003",
                            Street = "Leśna 10",
                            UpdatedAt = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            City = "Wrocław",
                            ClientId = 4,
                            Country = "Polska",
                            CreatedAt = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "50-004",
                            Street = "Polna 3",
                            UpdatedAt = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            City = "Poznań",
                            ClientId = 5,
                            Country = "Polska",
                            CreatedAt = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "60-005",
                            Street = "Szkolna 7",
                            UpdatedAt = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            City = "Łódź",
                            ClientId = 6,
                            Country = "Polska",
                            CreatedAt = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "90-006",
                            Street = "Ogrodowa 12",
                            UpdatedAt = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            City = "Katowice",
                            ClientId = 7,
                            Country = "Polska",
                            CreatedAt = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "40-007",
                            Street = "Lipowa 9",
                            UpdatedAt = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            City = "Lublin",
                            ClientId = 8,
                            Country = "Polska",
                            CreatedAt = new DateTime(2020, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "20-008",
                            Street = "Brzozowa 15",
                            UpdatedAt = new DateTime(2020, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            City = "Szczecin",
                            ClientId = 9,
                            Country = "Polska",
                            CreatedAt = new DateTime(2001, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "70-009",
                            Street = "Wiślana 20",
                            UpdatedAt = new DateTime(2001, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            City = "Bydgoszcz",
                            ClientId = 10,
                            Country = "Polska",
                            CreatedAt = new DateTime(2020, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            PostalCode = "85-010",
                            Street = "Zielona 8",
                            UpdatedAt = new DateTime(2020, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryBlazorApp.Domain.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Polski pisarz specjalizujący się w literaturze kryminalnej i thrillerach psychologicznych.",
                            BirthDate = new DateTime(1980, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Jan",
                            Nationality = "Polska",
                            Surname = "Kowalski",
                            UpdatedAt = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Autorka bestsellerowych powieści obyczajowych i romansów.",
                            BirthDate = new DateTime(1975, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Anna",
                            Nationality = "Polska",
                            Surname = "Nowak",
                            UpdatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Twórca epickich powieści fantasy inspirowanych mitologią słowiańską.",
                            BirthDate = new DateTime(1990, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Marek",
                            Nationality = "Polska",
                            Surname = "Zieliński",
                            UpdatedAt = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Pisarka science fiction, koncentrująca się na sztucznej inteligencji i przyszłości technologii.",
                            BirthDate = new DateTime(1985, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Katarzyna",
                            Nationality = "Polska",
                            Surname = "Wiśniewska",
                            UpdatedAt = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Autor książek popularnonaukowych z zakresu psychologii i rozwoju osobistego.",
                            BirthDate = new DateTime(1978, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tomasz",
                            Nationality = "Polska",
                            Surname = "Lewandowski",
                            UpdatedAt = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Autor pozostający w ukryciu. Tożsamość nieznana, brak potwierdzonych informacji biograficznych.",
                            CreatedAt = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Anonim",
                            Nationality = "Nieznana",
                            Surname = "",
                            UpdatedAt = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryBlazorApp.Domain.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tajemnicza historia książki i jej autora",
                            Quantity = 5,
                            Title = "Cień Wiatru",
                            UpdatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thriller technologiczny o sztucznej inteligencji",
                            Quantity = 3,
                            Title = "Kod Przeznaczenia",
                            UpdatedAt = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fantastyczna opowieść o upadłym królestwie",
                            Quantity = 7,
                            Title = "Ostatni Strażnik",
                            UpdatedAt = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CreatedAt = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kryminał noir w futurystycznym świecie",
                            Quantity = 4,
                            Title = "Miasto Cieni",
                            UpdatedAt = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CreatedAt = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Popularnonaukowa książka o psychologii",
                            Quantity = 6,
                            Title = "Sekrety Umysłu",
                            UpdatedAt = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Zagadka ukryta w historii",
                            Quantity = 2,
                            Title = "Zaginiony Symbol",
                            UpdatedAt = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Filozofia i rozwój osobisty",
                            Quantity = 8,
                            Title = "Droga Wojownika",
                            UpdatedAt = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2020, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Saga rodzinna na przestrzeni pokoleń",
                            Quantity = 3,
                            Title = "Echo Przeszłości",
                            UpdatedAt = new DateTime(2020, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 4,
                            CreatedAt = new DateTime(2001, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sci-fi o podróżach między wymiarami",
                            Quantity = 5,
                            Title = "Granice Rzeczywistości",
                            UpdatedAt = new DateTime(2001, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 5,
                            CreatedAt = new DateTime(2020, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dramat psychologiczny",
                            Quantity = 4,
                            Title = "Czas Milczenia",
                            UpdatedAt = new DateTime(2020, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fantastyczna historia o manipulacji snami",
                            Quantity = 6,
                            Title = "Złodziej Snów",
                            UpdatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 2,
                            CreatedAt = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Śledztwo pełne zwrotów akcji",
                            Quantity = 2,
                            Title = "Labirynt Prawdy",
                            UpdatedAt = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 3,
                            CreatedAt = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Epicka fantasy o walce o tron",
                            Quantity = 9,
                            Title = "Królestwo Popiołów",
                            UpdatedAt = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 4,
                            CreatedAt = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Programista odkrywa globalny spisek",
                            Quantity = 3,
                            Title = "Algorytm Chaosu",
                            UpdatedAt = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 5,
                            CreatedAt = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kryminał sądowy",
                            Quantity = 5,
                            Title = "Milczący Świadek",
                            UpdatedAt = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kosmiczna ekspedycja",
                            Quantity = 7,
                            Title = "Podróż bez Powrotu",
                            UpdatedAt = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Genetyka i przyszłość ludzkości",
                            Quantity = 4,
                            Title = "Tajemnice DNA",
                            UpdatedAt = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2020, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Historia wielkiego państwa",
                            Quantity = 6,
                            Title = "Upadek Imperium",
                            UpdatedAt = new DateTime(2020, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 1,
                            CreatedAt = new DateTime(2001, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Thriller polityczny",
                            Quantity = 2,
                            Title = "Czarna Lista",
                            UpdatedAt = new DateTime(2001, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 6,
                            CreatedAt = new DateTime(2020, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Inspirująca opowieść o nadziei",
                            Quantity = 8,
                            Title = "Światło w Ciemności",
                            UpdatedAt = new DateTime(2020, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryBlazorApp.Domain.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "adam.nowicki@example.com",
                            Name = "Adam",
                            PhoneNumber = "500100200",
                            Surname = "Nowicki",
                            UpdatedAt = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ewa.kaczmarek@example.com",
                            Name = "Ewa",
                            PhoneNumber = "501200300",
                            Surname = "Kaczmarek",
                            UpdatedAt = new DateTime(2023, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "piotr.mazur@example.com",
                            Name = "Piotr",
                            PhoneNumber = "502300400",
                            Surname = "Mazur",
                            UpdatedAt = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "karolina.dabrowska@example.com",
                            Name = "Karolina",
                            PhoneNumber = "503400500",
                            Surname = "Dąbrowska",
                            UpdatedAt = new DateTime(2021, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "michal.piotrowski@example.com",
                            Name = "Michał",
                            PhoneNumber = "504500600",
                            Surname = "Piotrowski",
                            UpdatedAt = new DateTime(2020, 9, 3, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "natalia.grabowska@example.com",
                            Name = "Natalia",
                            PhoneNumber = "505600700",
                            Surname = "Grabowska",
                            UpdatedAt = new DateTime(2022, 2, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "krzysztof.pawlak@example.com",
                            Name = "Krzysztof",
                            PhoneNumber = "506700800",
                            Surname = "Pawlak",
                            UpdatedAt = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2020, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "magdalena.michalska@example.com",
                            Name = "Magdalena",
                            PhoneNumber = "507800900",
                            Surname = "Michalska",
                            UpdatedAt = new DateTime(2020, 12, 24, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2001, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pawel.krol@example.com",
                            Name = "Paweł",
                            PhoneNumber = "508900100",
                            Surname = "Król",
                            UpdatedAt = new DateTime(2001, 5, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2020, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "agnieszka.wieczorek@example.com",
                            Name = "Agnieszka",
                            PhoneNumber = "509100200",
                            Surname = "Wieczorek",
                            UpdatedAt = new DateTime(2020, 8, 17, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryBlazorApp.Domain.Models.LibraryCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("LibraryCards", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            CreatedAt = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            CreatedAt = new DateTime(2022, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            CreatedAt = new DateTime(2021, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 4,
                            CreatedAt = new DateTime(2020, 7, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 5,
                            CreatedAt = new DateTime(2019, 9, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 6,
                            CreatedAt = new DateTime(2018, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 7,
                            CreatedAt = new DateTime(2017, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 8,
                            CreatedAt = new DateTime(2016, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 9,
                            CreatedAt = new DateTime(2015, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 10,
                            CreatedAt = new DateTime(2014, 8, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryBlazorApp.Domain.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LibraryCardId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("LibraryCardId");

                    b.ToTable("Loans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            BorrowDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            BorrowDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 1,
                            ReturnedDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            BookId = 3,
                            BorrowDate = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 2,
                            ReturnedDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            BookId = 4,
                            BorrowDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 3
                        },
                        new
                        {
                            Id = 5,
                            BookId = 5,
                            BorrowDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 3
                        },
                        new
                        {
                            Id = 6,
                            BookId = 6,
                            BorrowDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 3,
                            ReturnedDate = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            BookId = 7,
                            BorrowDate = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 4,
                            ReturnedDate = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            BookId = 8,
                            BorrowDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 5
                        },
                        new
                        {
                            Id = 9,
                            BookId = 9,
                            BorrowDate = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 5
                        },
                        new
                        {
                            Id = 10,
                            BookId = 10,
                            BorrowDate = new DateTime(2024, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 5,
                            ReturnedDate = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            BookId = 11,
                            BorrowDate = new DateTime(2024, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 5,
                            ReturnedDate = new DateTime(2024, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            BookId = 12,
                            BorrowDate = new DateTime(2024, 3, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 6,
                            ReturnedDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            BookId = 13,
                            BorrowDate = new DateTime(2024, 3, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 6,
                            ReturnedDate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            BookId = 14,
                            BorrowDate = new DateTime(2024, 3, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 7
                        },
                        new
                        {
                            Id = 15,
                            BookId = 15,
                            BorrowDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 7
                        },
                        new
                        {
                            Id = 16,
                            BookId = 16,
                            BorrowDate = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 7,
                            ReturnedDate = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 17,
                            BookId = 17,
                            BorrowDate = new DateTime(2024, 4, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 8,
                            ReturnedDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 18,
                            BookId = 18,
                            BorrowDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 9
                        },
                        new
                        {
                            Id = 19,
                            BookId = 19,
                            BorrowDate = new DateTime(2024, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 9
                        },
                        new
                        {
                            Id = 20,
                            BookId = 20,
                            BorrowDate = new DateTime(2024, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 9
                        },
                        new
                        {
                            Id = 21,
                            BookId = 1,
                            BorrowDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 9,
                            ReturnedDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 22,
                            BookId = 2,
                            BorrowDate = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 9,
                            ReturnedDate = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 23,
                            BookId = 3,
                            BorrowDate = new DateTime(2024, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 10,
                            ReturnedDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 24,
                            BookId = 4,
                            BorrowDate = new DateTime(2024, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LibraryCardId = 10,
                            ReturnedDate = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LibraryBlazorApp.Domain.Models.Address", b =>
                {
                    b.HasOne("LibraryBlazorApp.Domain.Models.Client", "Client")
                        .WithOne("Address")
                        .HasForeignKey("LibraryBlazorApp.Domain.Models.Address", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LibraryBlazorApp.Domain.Models.Book", b =>
                {
                    b.HasOne("LibraryBlazorApp.Domain.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LibraryBlazorApp.Domain.Models.LibraryCard", b =>
                {
                    b.HasOne("LibraryBlazorApp.Domain.Models.Client", "Client")
                        .WithOne("LibraryCard")
                        .HasForeignKey("LibraryBlazorApp.Domain.Models.LibraryCard", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LibraryBlazorApp.Domain.Models.Loan", b =>
                {
                    b.HasOne("LibraryBlazorApp.Domain.Models.Book", "Book")
                        .WithMany("Loans")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryBlazorApp.Domain.Models.LibraryCard", "LibraryCard")
                        .WithMany("Loans")
                        .HasForeignKey("LibraryCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("LibraryCard");
                });

            modelBuilder.Entity("LibraryBlazorApp.Domain.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryBlazorApp.Domain.Models.Book", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("LibraryBlazorApp.Domain.Models.Client", b =>
                {
                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("LibraryCard")
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryBlazorApp.Domain.Models.LibraryCard", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
